version: "3"

services:
  elasticsearch:
    build: 
        context: .
        dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    tty: true
    volumes:
      - ./es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
    environment:
        - "ELASTICSEARCH_URL=http://elasticsearch:9200"
        - "I18N_LOCALE=ja-JP"



# curl -H 'Content-Type: application/x-ndjson' -XPOST 'localhost:9200/bank/account/_bulk?pretty' --data-binary @accounts.json
